<?php

namespace App\Models\Backend\BatchExamManagement;

use App\Models\Backend\OrderManagement\ParentOrder;
use App\Models\Scopes\Searchable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class BatchExamSubscription extends Model
{
    use HasFactory;
    use Searchable;

    protected $fillable = [
        'batch_exam_id',
        'price',
        'package_duration_in_days',
        'discount_type',
        'discount_start_date',
        'discount_start_date_timestamp',
        'discount_end_date_timestamp',
        'discount_end_date',
        'status',
        'package_title',
        'discount_amount'
    ];

    protected $searchableFields = ['*'];

    protected $table = 'batch_exam_subscriptions';

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function ($sub){
//            if (isset($sub->contactMessages) && !empty($sub->contactMessages))
//            {
//                $sub->contactMessages->each->delete();
//            }
        });
    }

    public static function createOrUpdateSubscription($request, $batchExamId)
    {
        foreach ($request->price as $key => $singlePrice)
        {
            static::create([
                'batch_exam_id' => $batchExamId,
                'price' => $singlePrice,
                'package_title'  => $request->package_title[$key],
                'package_duration_in_days'  => $request->package_duration_in_days[$key],
                'discount_type' => $request->discount_type[$key],
                'discount_amount' => $request->discount_amount[$key],
                'discount_start_date'   => $request->discount_start_date[$key],
                'discount_start_date_timestamp' => strtotime($request->discount_start_date[$key]),
                'discount_end_date_timestamp'   => strtotime($request->discount_end_date[$key]),
                'discount_end_date' => $request->discount_end_date[$key],
                'status'    => 1,
            ]);
        }
    }
    public static function importBatchExamSubcriptionsJson($batchExamSubcriptions, $batchExamId)
    {
        foreach ($batchExamSubcriptions as $key => $batchExamSubcription)
        {
            static::create([
                'batch_exam_id' => $batchExamId,
                'price' => $batchExamSubcription->price,
                'package_title'  => $batchExamSubcription->package_title,
                'package_duration_in_days'  => $batchExamSubcription->package_duration_in_days,
                'discount_type' => $batchExamSubcription->discount_type,
                'discount_amount' => $batchExamSubcription->discount_amount,
                'discount_start_date'   => $batchExamSubcription->discount_start_date,
                'discount_start_date_timestamp' => $batchExamSubcription->discount_start_date_timestamp,
                'discount_end_date_timestamp'   => $batchExamSubcription->discount_end_date_timestamp,
                'discount_end_date' => $batchExamSubcription->discount_end_date,
                'status'    => $batchExamSubcription->status,
            ]);
        }
    }

    public function batchExam()
    {
        return $this->belongsTo(BatchExam::class);
    }

    public function parentOrders()
    {
        return $this->hasMany(ParentOrder::class);
//        return $this->hasMany(ParentOrder::class)->where('ordered_for', 'batch_exam');
    }
}
