<?php

namespace App\Models\Backend\NoticeManagement;

use App\Models\Scopes\Searchable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class NoticeCategory extends Model
{
    use HasFactory;
    use Searchable;

    protected $fillable = [
        'notice_category_id',
        'name',
        'image',
        'slug',
        'status',
    ];

    protected $searchableFields = ['*'];

    protected $table = 'notice_categories';

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function ($noticeCategory){
            if (file_exists($noticeCategory->image))
            {
                unlink($noticeCategory->image);
            }
            if (isset($noticeCategory->noticeCategories))
            {
                foreach ($noticeCategory->noticeCategories as $category)
                {
                    if (file_exists($category->image))
                    {
                        unlink($category->image);
                    }
                    $category->delete();
                }
            }
        });
    }

    protected static $noticeCategory;

    public static function createOrUpdateNoticeCategory($request, $id = null)
    {
        if ($id)
        {
            self::$noticeCategory = NoticeCategory::find($id);
        }else{
            self::$noticeCategory = new NoticeCategory();
        }
        if (!empty($request->notice_category_id))
        {
            self::$noticeCategory->notice_category_id = $request->notice_category_id;
        }else{
            self::$noticeCategory->notice_category_id = 0;
        }
        self::$noticeCategory->name = $request->name;
        self::$noticeCategory->image = isset($id) ? imageUpload($request->file('image'), 'notice-management/notice-categories/', 'notice-category-', '', '', NoticeCategory::find($id)->image) : imageUpload($request->file('image'), 'notice-management/notice-categories/', 'notice-category-', '', '');
        self::$noticeCategory->slug = str_replace(' ', '-', $request->name);
        self::$noticeCategory->status = $request->status == 'on' ? 1 : 0;
        self::$noticeCategory->save();
    }

    public function noticeCategory()
    {
        return $this->belongsTo(NoticeCategory::class);
    }

    public function noticeCategories()
    {
        return $this->hasMany(NoticeCategory::class, 'notice_category_id');
    }

    public function notices()
    {
        return $this->hasMany(Notice::class);
    }
}
